{% set name = "typepigeon" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typepigeon-{{ version }}.tar.gz
  sha256: 279c08f017f7841a0a06a4d411dbee10f3940972549f6863e0ad2b331e021b95

build:
  noarch: python
  script_env:
    - __version__={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - importlib-metadata
    - pyproj
    - python >=3.6
    - python-dateutil
    - shapely

test:
  imports:
    - typepigeon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://typepigeon.readthedocs.io
  summary: Python type converter
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/zacharyburnett/TypePigeon

extra:
  recipe-maintainers:
    - zacharyburnett
